# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f5c94868a984e03524b6b0b565b1005c47adf091783213a4d280845251287fb72e0012a6f390a53859721c37ef51400b7972eac8c29283d02779a1be92d9a4c

test:
  secret_key_base: 8ee94898074fa78c53bb038a9d4ca86a615b0fd73a9a261c536674c88560a3227d6b48395fc2d3dfc2dc3249b0919c2c807eef17d06f07f99a639777aa408f21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
